### ISSUE TITLE
code generated is not valid

### ISSUE THREAD

**Issue by iulian0512** [gaetschwartz/freezed#2]
all steps to reproduce in the attached gif
![freezed](https://user-images.githubusercontent.com/16035099/105334170-3d58da80-5bdf-11eb-846a-91e6dd42a016.gif)

**Comment by gaetschwartz** [comment]
Hi, you're probably missing `json_serializable` in your` pubspec.yaml` and it thus doesn't generate the toJson/fromJson file (`.g.dart`).
