### ISSUE TITLE
Stuck at Initializing

### ISSUE THREAD

**Issue by 2shrestha22** [gaetschwartz/freezed#3]
When using watch from status bar it keeps initializing. It never completes while `flutter pub run build_runner watch --delete-conflicting-outputs` works fine.

Also generating freezed class give error:
```Command 'Freezed: Generate a new Freezed class' resulted in an error (Running the contributed command: 'freezed.generate' failed.)```

I think problem is with my IDE maybe. 

```
Code - OSS
Version: 1.54.2
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-12T19:27:39.374Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.11.7-arch1-1
```

**Comment by craigomac** [comment]
I have the same issue. Nothing but this:

![image](https://user-images.githubusercontent.com/6972172/113447942-27477180-93fb-11eb-8770-0dabb3ab4ff2.png)

**Comment by gaetschwartz** [comment]
Hi @craigomac @2shrestha22, I think I know why this is happening, will try to fix it in the upcoming week !

**Comment by yerzhant** [comment]
Hi, the similar issue:
![image](https://user-images.githubusercontent.com/11594067/113605173-18192b80-9668-11eb-8dd3-152d9aeadf76.png)

Version: 1.55.0
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:02:21.560Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-70-generic snap

**Comment by yerzhant** [comment]
![image](https://user-images.githubusercontent.com/11594067/113605370-5dd5f400-9668-11eb-934f-2f009a667d94.png)

**Comment by gaetschwartz** [comment]
I'm currently working on 1.0 which will most likely fix this issue, will keep you updated.

**Comment by yerzhant** [comment]
Thanks!

**Comment by gaetschwartz** [comment]
You can mainly track the progress here: https://twitter.com/gaetschwartz/status/1379401791847153665?s=20

**Comment by gaetschwartz** [comment]
Hey, support for `build_runner` moved to a separate extension (https://marketplace.visualstudio.com/items?itemName=GaetSchwartz.build-runner). Feel free to check it out and send feedback to the [new repo](https://github.com/gaetschwartz/build-runner). 

Moved this issue to https://github.com/gaetschwartz/build-runner/issues/1.
